spring:
  datasource:
    url: jdbc:mysql://localhost:3306/engage_bcc
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show_sql: false
      format_sql: false
      ddl-auto: update

config:
  external-apis:
    connect-timeout: 20000
    read-timeout: 20000

  business:
    vat-rate: 0.2